site_name: Ontology Design Patterns for Materials Science and Engineering
site_url: https://ise-fizkarlsruhe.github.io/odps4mse/
repo_url: https://github.com/ISE-FIZKarlsruhe/odps4mse
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - toc.follow
    - navigation.top
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences

plugins:
  - search:
      separator: '[\\s\\-_/]+|(?=[A-Z][a-z])'
      lang: en
      exclude: true
      boost: 2.0
  - gen-files:
      scripts:
        - docs/gen.py
  - macros

         

nav:
  - Introduction: index.md
  - Process ODPs: ProcessODPs.md
  - Ontologies: ontologies/index.md   # auto-generated 
  - Find Terms: terms/find.md
