
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT (STR(?e) AS ?ID) (STR(?lab) AS ?LABEL) (COALESCE(STR(?t), "") AS ?TYPE)
WHERE {
  ?e rdfs:label ?lab .
  OPTIONAL { ?e rdf:type ?t . }
}
ORDER BY LCASE(?LABEL)
